# Generated by Django 4.1.2 on 2022-10-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id_answer', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificaciones', models.IntegerField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('remitente', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('img_src', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_quest', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=350, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('passsword', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id_user_product', models.IntegerField(primary_key=True, serialize=False)),
                ('license_type', models.CharField(blank=True, max_length=50, null=True)),
                ('license_cad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id_user_session', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'user_session',
                'managed': False,
            },
        ),
    ]
